In [3]:
import numpy as np
import time

In [13]:
size = 100_000_000

# pylist
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"py list time = {end-start} secs")

# numpy_arrays
arr = np.array(py_list)
start = time.time()
sq_list = arr**2
end = time.time()
print(f"numpy list time = {end-start} secs")

py list time = 16.60136079788208 secs
numpy list time = 2.2002432346343994 secs


In [14]:
# memory
import sys
print(f"py list = {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"numpy array size = {arr.nbytes} bytes")

py list = 80000005600000000 bytes
numpy array size = 400000000 bytes


In [16]:
# shape
arr2D = np.array([[1,2],[3,4],[6,7]])
print(arr2D, arr2D.shape)
arr2D.shape

[[1 2]
 [3 4]
 [6 7]] (3, 2)


(3, 2)

In [20]:
# numpy 
arr0 = np.zeros(5, dtype="int64")
arr0

array([0, 0, 0, 0, 0], dtype=int64)

In [22]:
arr1 = np.ones((5,4), dtype="int64")
print(arr1, arr1.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (5, 4)


In [26]:
arr2 = np.full((5,4), 100)
print(arr2, arr1.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (5, 4)


In [28]:
# identity matrix
arr3 = np.eye(5, dtype="int64")
print(arr3)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [30]:
arr5 = np.arange(0,11,2)
arr5

array([ 0,  2,  4,  6,  8, 10])

In [37]:
arr6 = np.linspace(0,100,8)
print(arr6)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [38]:
# properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
int32
2


In [40]:
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [51]:
# operations on numpy
# reshaping
arr = np.array([(3,2), (2,3), (9,8)])
reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

[[3 2]
 [2 3]
 [9 8]] (3, 2)


In [54]:
flattend = arr.flatten()
print(flattend, flattend.shape)

[3 2 2 3 9 8] (6,)


In [8]:
# 3dimensional

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr))
print(np.sum(arr,axis=0)) # 0 = column wise vertical
print(np.sum(arr,axis=1)) # 1 = row wise 

45
[12 15 18]
[ 6 15 24]
